definitions:
  auth.LoginCredentials:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  auth.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  schema.EducationResponseSchema:
    properties:
      activities:
        type: string
      degree:
        type: string
      endDate:
        type: string
      gpa:
        type: string
      id:
        type: string
      major:
        type: string
      school:
        type: string
      startDate:
        type: string
    type: object
  schema.EducationUpdateSchema:
    properties:
      activities:
        type: string
      degree:
        type: string
      endDate:
        type: string
      gpa:
        type: string
      major:
        type: string
      school:
        type: string
      startDate:
        type: string
    type: object
  schema.Error:
    properties:
      error:
        properties:
          code:
            type: integer
          message:
            type: string
        type: object
    type: object
  schema.ExperienceResponseSchema:
    properties:
      company:
        type: string
      description:
        type: string
      endDate:
        type: string
      id:
        type: string
      location:
        type: string
      startDate:
        type: string
      title:
        type: string
    type: object
  schema.ExperienceUpdateSchema:
    properties:
      company:
        type: string
      description:
        type: string
      endDate:
        type: string
      location:
        type: string
      startDate:
        type: string
      title:
        type: string
    type: object
  schema.ProjectResponseSchema:
    properties:
      description:
        type: string
      endDate:
        type: string
      id:
        type: string
      skills:
        items:
          type: string
        type: array
      startDate:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  schema.ProjectUpdateSchema:
    properties:
      description:
        type: string
      endDate:
        type: string
      skills:
        items:
          type: string
        type: array
      startDate:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  schema.ResumeCreateSchema:
    properties:
      description:
        type: string
      public:
        type: boolean
      template:
        type: string
      title:
        minLength: 1
        type: string
    required:
    - title
    type: object
  schema.ResumeResponseSchema:
    properties:
      createdAt:
        type: string
      description:
        type: string
      educations:
        items:
          $ref: '#/definitions/schema.EducationResponseSchema'
        type: array
      email:
        type: string
      experiences:
        items:
          $ref: '#/definitions/schema.ExperienceResponseSchema'
        type: array
      id:
        type: string
      image:
        type: string
      projects:
        items:
          $ref: '#/definitions/schema.ProjectResponseSchema'
        type: array
      public:
        type: boolean
      skills:
        items:
          type: string
        type: array
      template:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  schema.ResumeUpdateSchema:
    properties:
      description:
        type: string
      educations:
        items:
          $ref: '#/definitions/schema.EducationUpdateSchema'
        type: array
      email:
        type: string
      experiences:
        items:
          $ref: '#/definitions/schema.ExperienceUpdateSchema'
        type: array
      image:
        type: string
      projects:
        items:
          $ref: '#/definitions/schema.ProjectUpdateSchema'
        type: array
      public:
        type: boolean
      skills:
        items:
          type: string
        type: array
      template:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  schema.UserCreateSchema:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  schema.UserResponseSchema:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  schema.UserUpdateSchema:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is an api api for Paperless.dev
  license:
    name: MIT
    url: https://raw.githubusercontent.com/hwangseonu/paperless.dev/refs/heads/main/LICENSE
  title: Paperless.dev API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: get tokens
      parameters:
      - description: login credentials info
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/auth.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      summary: login
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: get new access and refresh tokens using refresh token
      parameters:
      - description: Bearer {refresh_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      summary: refresh tokens
      tags:
      - Auth
  /resumes:
    get:
      description: get all resumes
      parameters:
      - description: Owner ID of resumes
        in: query
        name: user
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              resumes:
                items:
                  $ref: '#/definitions/schema.ResumeResponseSchema'
                type: array
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: get all resumes
      tags:
      - Resume
    post:
      consumes:
      - application/json
      description: create new resume
      parameters:
      - description: initial values of resume
        in: body
        name: resume
        required: true
        schema:
          $ref: '#/definitions/schema.ResumeCreateSchema'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            properties:
              resume:
                $ref: '#/definitions/schema.ResumeResponseSchema'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: create new resume
      tags:
      - Resume
  /resumes/{id}:
    delete:
      description: delete resume by id
      parameters:
      - description: Resume ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: delete resume by id
      tags:
      - Resume
    get:
      description: get resume by id
      parameters:
      - description: Resume ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              resume:
                $ref: '#/definitions/schema.ResumeResponseSchema'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: get resume by id
      tags:
      - Resume
    patch:
      description: update resume by id
      parameters:
      - description: Resume ID
        in: path
        name: id
        required: true
        type: string
      - description: update values of resume
        in: body
        name: resume
        required: true
        schema:
          $ref: '#/definitions/schema.ResumeUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              resume:
                $ref: '#/definitions/schema.ResumeResponseSchema'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: update resume by id
      tags:
      - Resume
  /users:
    post:
      consumes:
      - application/json
      description: create new user
      parameters:
      - description: initial values of user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/schema.UserCreateSchema'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            properties:
              user:
                $ref: '#/definitions/schema.UserResponseSchema'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      summary: create new user
      tags:
      - User
  /users/{id}:
    delete:
      description: delete user by id
      parameters:
      - description: User ID, Pass 'me' to delete your data.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: delete user by id
      tags:
      - User
    get:
      description: get user info by id
      parameters:
      - description: User ID, Pass 'me' to retrieve your data.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              user:
                $ref: '#/definitions/schema.UserResponseSchema'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: get user info by id
      tags:
      - User
    patch:
      description: update user data by id
      parameters:
      - description: User ID, Pass 'me' to delete your data.
        in: path
        name: id
        required: true
        type: string
      - description: update values of User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/schema.UserUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              user:
                $ref: '#/definitions/schema.UserResponseSchema'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/schema.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.Error'
      security:
      - BearerAuth: []
      summary: update user data by id
      tags:
      - User
securityDefinitions:
  BearerAuth:
    description: '"Type ''Bearer '' followed by your API key"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
